#ifndef __ANDRO_CMD_H__
#define __ANDRO_CMD_H__

#define ANDRO_BUSINESS_CMD_START 0
#define ANDRO_BUSINESS_CMD_PING (ANDRO_BUSINESS_CMD_START + 0)
#define ANDRO_BUSINESS_CMD_REGISTER (ANDRO_BUSINESS_CMD_START + 5)
#define ANDRO_BUSINESS_CMD_LOGIN ANDRO_BUSINESS_CMD_START + 6

#endif