name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: centos7

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: make memcheck
      run: |
        yum install -y valgrind
        make memcheck
