name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: intall deps
      run: sudo apt-get install valgrind 
    - name: make
      run: make
    - name: make memcheck
      run: make memcheck
