name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/centos:7

    steps:
    - uses: actions/checkout@v3
    - name: intall deps
      run: yum install -y valgrind gcc make
    - name: make
      run: make
    - name: make memcheck
      run: make memcheck
