name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: intall deps
      run: |
        sudo apt-get install cmake valgrind autoconf automake libtool unzip 
        git clone -b v3.21.12 https://github.com/protocolbuffers/protobuf.git 
        cd protobuf
        git submodule update --init --recursive 
        ./autogen.sh
        ./configure
        make 
        make check
        sudo make install
        sudo ldconfig 
    - name: Run Cmake
      run: cmake ..
    - name: Build
      run: |
        cd cmake-build-debug
        make
    - name: Run Valgrind Memcheck
      run: |
        cd cmake-build-debug
        make memcheck
