name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/silver2dream/andromeda-build-env:latest
    steps:
    - uses: actions/checkout@v3
    - name: Create build directory
      run: mkdir build && cd build
    - name: Run Protoc
      run: |
        ls .
        protoc -I=./proto --cpp_out=./generated ./proto/*.proto
    - name: Run CMake
      run: |
        cd build
        apt-get install -y g++
        cmake ..
    - name: Build
      run: |
        cd build
        make
    - name: Run Valgrind Memcheck
      run: |
        cd build
        #make memcheck
        /usr/bin/valgrind.bin --tool=memcheck --leak-check=full --show-reachable=yes --trace-children=yes --log-file=./valgrind.log ./andromeda
        cat ./valgrind.log
        #pgrep -f "/usr/bin/valgrind.bin --tool=memcheck --leak-check=full --show-reachable=yes --trace-children=yes --log-file=./valgrind.log ./andromeda" | xargs kill -9
        if grep -q "definitely lost: 0 bytes in 0 blocks" valgrind.log \
        && grep -q "indirectly lost: 0 bytes in 0 blocks" valgrind.log \
        && grep -q "possibly lost: 0 bytes in 0 blocks" valgrind.log; then
          echo "No memory leaks detected"
        else
          echo "Memory leaks detected"
          exit 1
        fi
    - name: Upload Valgrind Log
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: valgrind-logs
        path: valgrind.log
